### PR TITLE
Bring Ruby to 2.6

### PR DESCRIPTION
**Pull request by gliptak**
Signed-off-by: Gábor Lipták <gliptak@gmail.com>

### CODE REVIEW

**Comment by gliptak** [comment]
@erickascic please review

**Comment by Mr-Lizard** [comment]
I was hoping for some discussion on this - how feasible would this be ?

**Comment by gliptak** [comment]
@Mr-Lizard certainly. This simply brings ```Ruby``` to current stable.

**Comment by Mr-Lizard** [comment]
Sure, but why remove it before the project leads comment on it ?  It would seem to be A Good Thing, unless Eric has some reason for keeping it at the version its on.

**Comment by gliptak** [comment]
@Mr-Lizard thank you for the question. I keep unacknowledged PRs open for about 30 days hoping to receive at least an ```I cannot work this right now, but still hoping to get to it some day``` comment in that time period.

**Comment by Mr-Lizard** [comment]
Well, the admins are probably very busy, I recommend waiting a bit further
if it is no problem to you.

**Comment by gliptak** [comment]
I can't seem to reopen the PR so an Admin would have to do so.

**Comment by erickascic** [comment]
Sorry, late to the party.  We have a downstream consumer that we just recently forced to upgrade to 2.5.... so I'm a bit reluctant to force them again unless there is a compelling language feature.

**Pull request closed without merging**
