### PR TITLE
Add CircleCI badge to README

### PR DESCRIPTION
**Pull request by gliptak**

### CODE REVIEW

**Comment by gliptak** [comment]
@erickascic please review

**Comment by erickascic** [comment]
Hey - we're not using CircleCI any more.

**Comment by gliptak** [comment]
@erickascic You are commenting on CircleCI changes at https://github.com/stelligent/cfn_nag/pull/276

Do you still have a CI attached?

**Comment by erickascic** [comment]
@gliptak haven't decided on a new CI platform yet... hopefully in the next few weeks, will have something running.

**Pull request closed without merging**
