### PR TITLE
Create EBSEncryptionRule.rb

### PR DESCRIPTION
**Pull request by annasaphira**
Created new rule to check if EBS is encrypted.

### CODE REVIEW

**Comment by jesseadams** [comment]
Is this any different than Rule ID `F1` - https://github.com/stelligent/cfn_nag/blob/master/lib/cfn-nag/custom_rules/EbsVolumeHasSseRule.rb ?

I realize that `EbsVolumeHasSseRule` does need updated to use `BooleanBaseRule`, but otherwise I think it is the same.

**Comment by annasaphira** [comment]
Ok - that's right - we overlooked that - sorry - so you can use it as an update for the other rule. My team and I discuss another rule, that should check if parameter encryption_key has a value. Do you know if you have this in your development pipe?

**Comment by erickascic** [comment]
@annasaphira i don't believe we have an existing issue in our backlog for anything related to EC2::Volume. KmsKeyId.

There are a couple of options for how we could help you....

I'm not sure if we want to emit a failing violation for having no KmsKeyId.  Some ppl want the basic SSE and don't want to pay for and to manage KMS keys.... that said, we could either:

1. Add a rule to the core product where it is a warning, or...
2. We could write the rule as a violation and give you the code that you can use with a custom profile.

**Comment by annasaphira** [comment]
Thank you for your reply, we would prefer your first proposition. 
Can you tell us, when it will be released?

**Comment by jesseadams** [comment]
@annasaphira - Closing this in favor of https://github.com/stelligent/cfn_nag/issues/261

We will try to get this release within a week. Thanks for your patience.

**Comment by erickascic** [comment]
Released in 0.4.33

**Pull request closed without merging**
