### PR TITLE
Expose a Lambda nag over HTTP without CodeCommit hooks

### PR DESCRIPTION
**Pull request by craigw**
This is mostly a reworking of the code in the existing Lambda example, with a few tiny bug fixes. It shows how to expose CfnNag over HTTP when wrapped in a Lambda.

### CODE REVIEW

**Comment by venkatkotta** [comment]
Hi @craigw , i tried your changes to scan cloudformation template on my local machine but seems like it is not working properly every time i run #Use the lambda it throws a error , even though my cloudformation template is fine and scan works fine without lambda
{
  "failure_count": 1,
  "violations": [
    "FATAL FAIL Illegal cfn - no Resources "
  ]

**Comment by roberto-andrade** [comment]
Hello,

Could you please help me out on the following scenario:

I have a static web form that calls my AWS API, which triggers one lambda that runs the 'cfn_nag.audit' from the 'api_gateway_invoker.rb'.
I am passing the template file (.yaml) as a string in the JSON body using HTTP POST method.
The request JSON would be like this:
image

Here is the result (error):
image

- Am I missing some parameters in the request ?
- Does the file format would be byteArray or plain text ?
- Any other thoughts ?

Many Thanks !

**Comment by erickascic** [comment]
is there an earlier exception that wipes out the audit_result?  what does audit_result look like (this is actually cfn-nag-pipeline code vs. cfn-nag itself?)

**Comment by roberto-andrade** [comment]
Hi Erick,

Thanks for your support.

This code is cfn-nag-pipeline calling the 'api_gateway_invoker' from the Java Wrapper.

Here is the full exception log:
image

Many Thanks !

**Comment by erickascic** [comment]
I need some time to track down what changed/when, but I'm guessing that if on line 22 of api_gateway_invoker, you can change audit_result['failure_count'] to audit_result[:failure_count] to get past the failure.  the keys in audit_result are symbols not strings, so audit_result['failure_count'] will yield a nil and then nil > 0 raises the exception.

**Comment by erickascic** [comment]
Given that Lambda supports Ruby natively now, going to close this one out.  We'll have some work coming out soon to expose cfn_nag as a service but it won't leverage JRuby/java8

**Pull request closed without merging**
