### PR TITLE
Adding Pre commit config to allow for integration to the pre commit…

### PR DESCRIPTION
**Pull request by JBarnes94**
… framework

### CODE REVIEW

**Comment by erickascic** [comment]
@JBarnes94 can you explain this PR in more detail?  I'm not sure what this pre-commit hook has to do with cfn_nag.  thanks!

**Comment by JBarnes94** [comment]
As part of my local development I would like to be able to Run cfn_nag as a git pre commit hook to ensure I don't commit insecure template / It has to be a conscious  decision to do so by providing the  --no-verify flag.

To manage Pre Commit Hook i am using 
https://pre-commit.com/

> Pre-Commit is a multi-language package manager for pre-commit hooks. You specify a list of hooks you want and pre-commit manages the installation and execution of any hook

This PR will allow cfn-nag to be used with the pre commit framework. 

To run on the user side the following would need to be added to .pre-commit-config.yaml

```
repo: https://github.com/stelligent/cfn_nag
  rev: master
  hooks:
    - id: cfn-nag
```

Now you have added the --ignore-fatal
This can be added to run as default too, so when run as a pre commit hook all json, yaml, template files, can be check and if they contain Cloudformation code do security checkin on them

**Comment by joel-aws** [comment]
Adding another opinion that this would be very helpful in our workflow. Currently, we have to fork this repository and add `.pre-commit-config.yaml` so that we can reference it when running `pre-commit`. Along with cfn-nag, we also use [pre-commit](https://github.com/pre-commit/pre-commit) to check our commits against flake8, black, cfn-python-lint, and prettier -- all of which have pre-commit config files in their repositories.

**Comment by ikben** [comment]
To add some more information:

- Here is an AWS blog post about doing that with cfn-lint: https://aws.amazon.com/blogs/mt/git-pre-commit-validation-of-aws-cloudformation-templates-with-cfn-lint/
- And the cfn-lint configuration: https://github.com/aws-cloudformation/cfn-python-lint/blob/master/.pre-commit-hooks.yaml
- The official pre-commit website: https://pre-commit.com/

**Comment by ikben** [comment]
@JBarnes94 @joel-aws 

I'm using this in my `.pre-commit-config.yaml` as a workaround:

```
repos:
  # Can be changed if https://github.com/stelligent/cfn_nag/pull/469 gets merged
  - repo: local
    hooks:
      -   id: cfn-nag
          name: Cloudformation Nag
          description: This hook Alerts on Cloudformation insecurities 
          entry: cfn_nag_scan --input-path
          language: ruby
          files: \.(json|yaml|yml|template)$
          # This will run gem install
          additional_dependencies:
            - cfn-nag
```

**Comment by joel-aws** [comment]
@erickascic Would you like any more info on this PR? Just wanted to re-affirm that cfn_nag is awesome and essential to our development process; this PR would be a big help in streamlining our use of it.

**Comment by mariadb-JeffBachtel** [comment]
@thegonch can you review and merge? This got missed when Eric left, I think (and it's a great and super easy feature to support)

**Comment by thegonch** [comment]
Apologies for the long delay in reviewing this.  This looks like a great addition to cfn_nag.  @JBarnes94 This will require updating the fork first with the latest from the master branch of cfn_nag.  Once this is done, I'll be happy to merge it.

**Comment by arothian** [comment]
Addressed in #538

**Pull request closed without merging**
